% function [T1,T2,T3,T4,T5] = CHIP5_20240606_SAtest
function [T1,T2,T3,T4,T5] = CHIP5_20240606_SAtest(X1,Y1,X2,Y2,X3,Y3,X4,Y4,X5,Y5,pcbL,pcbW,pcbH,...
                                                    L1,W1,H1,L2,W2,H2,L3,W3,H3,L4,W4,H4,L5,W5,H5,level)
%
% CHIP5_20240606_SAtest.m
%
% Model exported on Jun 6 2024, 14:40 by COMSOL 6.1.0.252.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

%model.modelPath(['C:\Users\Misato\Desktop\SA' native2unicode(hex2dec({'6d' '4b'}), 'unicode')  native2unicode(hex2dec({'8b' 'd5'}), 'unicode')  native2unicode(hex2dec({'4f' '7f'}), 'unicode')  native2unicode(hex2dec({'75' '28'}), 'unicode') ]);

model.label('CHIP5-20240606-SAtest.mph');

% model.param.set('CHIPX1', '30');
% model.param.set('CHIPY1', '75');
% model.param.set('CHIPX2', '135');
% model.param.set('CHIPY2', '120');
% model.param.set('CHIPX3', '75');
% model.param.set('CHIPY3', '120');
% model.param.set('CHIPX4', '90');
% model.param.set('CHIPY4', '30');
% model.param.set('CHIPX5', '75');
% model.param.set('CHIPY5', '75');
model.param.set('CHIPX1', num2str(X1));
model.param.set('CHIPY1', num2str(Y1));
model.param.set('CHIPX2', num2str(X2));
model.param.set('CHIPY2', num2str(Y2));
model.param.set('CHIPX3', num2str(X3));
model.param.set('CHIPY3', num2str(Y3));
model.param.set('CHIPX4', num2str(X4));
model.param.set('CHIPY4', num2str(Y4));
model.param.set('CHIPX5', num2str(X5));
model.param.set('CHIPY5', num2str(Y5));

model.component.create('comp1', true);

model.component('comp1').geom.create('geom1', 3);

model.result.table.create('evl3', 'Table');
model.result.table.create('tbl1', 'Table');

model.component('comp1').mesh.create('mesh1');

model.component('comp1').geom('geom1').lengthUnit('mm');
model.component('comp1').geom('geom1').create('blk1', 'Block');
model.component('comp1').geom('geom1').feature('blk1').label('PCB');
model.component('comp1').geom('geom1').feature('blk1').set('pos', [-5 -5 -13]);
model.component('comp1').geom('geom1').feature('blk1').set('size', [pcbL pcbW pcbH]);
model.component('comp1').geom('geom1').create('blk2', 'Block');
model.component('comp1').geom('geom1').feature('blk2').label('CHIP1');
model.component('comp1').geom('geom1').feature('blk2').set('pos', {'CHIPX1' 'CHIPY1' '2'});
model.component('comp1').geom('geom1').feature('blk2').set('size', [L1 W1 H1]);
model.component('comp1').geom('geom1').create('blk3', 'Block');
model.component('comp1').geom('geom1').feature('blk3').label('CHIP2');
model.component('comp1').geom('geom1').feature('blk3').set('pos', {'CHIPX2' 'CHIPY2' '2'});
model.component('comp1').geom('geom1').feature('blk3').set('size', [L2 W2 H2]);
model.component('comp1').geom('geom1').create('blk4', 'Block');
model.component('comp1').geom('geom1').feature('blk4').label('CHIP3');
model.component('comp1').geom('geom1').feature('blk4').set('pos', {'CHIPX3' 'CHIPY3' '2'});
model.component('comp1').geom('geom1').feature('blk4').set('size', [L3 W3 H3]);
model.component('comp1').geom('geom1').create('blk5', 'Block');
model.component('comp1').geom('geom1').feature('blk5').label('CHIP4');
model.component('comp1').geom('geom1').feature('blk5').set('pos', {'CHIPX4' 'CHIPY4' '2'});
model.component('comp1').geom('geom1').feature('blk5').set('size', [L4 W4 H4]);
model.component('comp1').geom('geom1').create('blk7', 'Block');
model.component('comp1').geom('geom1').feature('blk7').label('AIR');
model.component('comp1').geom('geom1').feature('blk7').set('pos', [-10 -10 -15]);
model.component('comp1').geom('geom1').feature('blk7').set('size', [225 165 50]);
model.component('comp1').geom('geom1').create('wp1', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp1').set('planetype', 'faceparallel');
model.component('comp1').geom('geom1').feature('wp1').set('unite', true);
model.component('comp1').geom('geom1').feature('wp1').selection('face').set('blk1(1)', 4);
model.component('comp1').geom('geom1').create('par1', 'Partition');
model.component('comp1').geom('geom1').feature('par1').set('partitionwith', 'workplane');
model.component('comp1').geom('geom1').feature('par1').selection('input').set({'blk1'});
model.component('comp1').geom('geom1').create('wp2', 'WorkPlane');
model.component('comp1').geom('geom1').feature('wp2').set('planetype', 'faceparallel');
model.component('comp1').geom('geom1').feature('wp2').set('unite', true);
model.component('comp1').geom('geom1').feature('wp2').selection('face').set('par1(1)', 3);
model.component('comp1').geom('geom1').create('par2', 'Partition');
model.component('comp1').geom('geom1').feature('par2').set('partitionwith', 'workplane');
model.component('comp1').geom('geom1').feature('par2').selection('input').set({'par1'});
model.component('comp1').geom('geom1').create('blk8', 'Block');
model.component('comp1').geom('geom1').feature('blk8').label('CHIP5');
model.component('comp1').geom('geom1').feature('blk8').set('pos', {'CHIPX5' 'CHIPY5' '2'});
model.component('comp1').geom('geom1').feature('blk8').set('size', [L5 W5 H5]);
model.component('comp1').geom('geom1').run;
model.component('comp1').geom('geom1').run('fin');

model.component('comp1').selection.create('sel1', 'Explicit');
model.component('comp1').selection('sel1').geom('geom1', 2);
model.component('comp1').selection('sel1').set([17 18 20 21 30]);
model.component('comp1').selection.create('sel2', 'Explicit');
model.component('comp1').selection('sel2').geom('geom1', 2);
model.component('comp1').selection('sel2').set([17 18 20 21 30]);
model.component('comp1').selection.create('sel3', 'Explicit');
model.component('comp1').selection('sel3').geom('geom1', 2);
model.component('comp1').selection('sel3').set([11 16 38]);
model.component('comp1').selection('sel1').label([native2unicode(hex2dec({'88' '68'}), 'unicode')  native2unicode(hex2dec({'97' '62'}), 'unicode')  native2unicode(hex2dec({'8f' '90'}), 'unicode')  native2unicode(hex2dec({'5c' '04'}), 'unicode') ]);
model.component('comp1').selection('sel3').label('connect');

model.component('comp1').view('view3').tag('view31');
model.component('comp1').view('view2').tag('view3');
model.component('comp1').view('view31').tag('view4');

model.component('comp1').material.create('mat1', 'Common');
model.component('comp1').material.create('mat3', 'Common');
model.component('comp1').material.create('mat5', 'Common');
model.component('comp1').material.create('mat6', 'Common');
model.component('comp1').material.create('mat7', 'Common');
model.component('comp1').material.create('mat8', 'Common');
model.component('comp1').material('mat1').selection.set([1]);
model.component('comp1').material('mat1').propertyGroup('def').func.create('eta', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('Cp', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('rho', 'Analytic');
model.component('comp1').material('mat1').propertyGroup('def').func.create('k', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func.create('cs', 'Analytic');
model.component('comp1').material('mat1').propertyGroup('def').func.create('an1', 'Analytic');
model.component('comp1').material('mat1').propertyGroup('def').func.create('an2', 'Analytic');
model.component('comp1').material('mat1').propertyGroup.create('RefractiveIndex', 'Refractive index');
model.component('comp1').material('mat1').propertyGroup.create('NonlinearModel', 'Nonlinear model');
model.component('comp1').material('mat1').propertyGroup.create('idealGas', 'Ideal gas');
model.component('comp1').material('mat1').propertyGroup('idealGas').func.create('Cp', 'Piecewise');
model.component('comp1').material('mat3').selection.set([2]);
model.component('comp1').material('mat3').propertyGroup.create('Enu', 'Young''s modulus and Poisson''s ratio');
model.component('comp1').material('mat5').selection.set([3 4 5 6 7]);
model.component('comp1').material('mat5').propertyGroup.create('Enu', 'Young''s modulus and Poisson''s ratio');
model.component('comp1').material('mat5').propertyGroup.create('RefractiveIndex', 'Refractive index');
model.component('comp1').material('mat6').selection.named('sel3');
model.component('comp1').material('mat6').propertyGroup.create('shell', [native2unicode(hex2dec({'58' 'f3'}), 'unicode') ]);
model.component('comp1').material('mat7').selection.geom('geom1', 1);
model.component('comp1').material('mat7').propertyGroup.create('Enu', 'Young''s modulus and Poisson''s ratio');
model.component('comp1').material('mat8').selection.geom('geom1', 2);
model.component('comp1').material('mat8').selection.set([8 9 13 19 24 29]);
model.component('comp1').material('mat8').propertyGroup.create('Enu', 'Young''s modulus and Poisson''s ratio');
model.component('comp1').material('mat8').propertyGroup.create('linzRes', 'Linearized resistivity');

model.component('comp1').physics.create('ht', 'HeatTransferInSolidsAndFluids', 'geom1');
model.component('comp1').physics('ht').feature('fluid1').selection.set([1]);
model.component('comp1').physics('ht').create('hs1', 'HeatSource', 3);
model.component('comp1').physics('ht').feature('hs1').selection.set([3]);
model.component('comp1').physics('ht').create('sls1', 'SolidLayeredShell', 2);
model.component('comp1').physics('ht').feature('sls1').selection.named('sel3');
model.component('comp1').physics('ht').create('temp1', 'TemperatureBoundary', 2);
model.component('comp1').physics('ht').feature('temp1').selection.set([3]);
model.component('comp1').physics('ht').create('hs2', 'HeatSource', 3);
model.component('comp1').physics('ht').feature('hs2').selection.set([7]);
model.component('comp1').physics('ht').create('hs3', 'HeatSource', 3);
model.component('comp1').physics('ht').feature('hs3').selection.set([5]);
model.component('comp1').physics('ht').create('hs4', 'HeatSource', 3);
model.component('comp1').physics('ht').feature('hs4').selection.set([6]);
model.component('comp1').physics('ht').create('hs5', 'HeatSource', 3);
model.component('comp1').physics('ht').feature('hs5').selection.set([4]);
model.component('comp1').physics('ht').create('hf1', 'HeatFluxBoundary', 2);
model.component('comp1').physics('ht').feature('hf1').selection.all;



model.component('comp1').probe.create('dom9', 'Domain');
model.component('comp1').probe.create('dom8', 'Domain');
model.component('comp1').probe.create('dom7', 'Domain');
model.component('comp1').probe.create('dom6', 'Domain');
model.component('comp1').probe.create('dom5', 'Domain');
model.component('comp1').probe('dom9').selection.set([3]);
model.component('comp1').probe('dom8').selection.set([7]);
model.component('comp1').probe('dom7').selection.set([5]);
model.component('comp1').probe('dom6').selection.set([6]);
model.component('comp1').probe('dom5').selection.set([4]);

model.result.table('evl3').label('Evaluation 3D');
model.result.table('evl3').comments([native2unicode(hex2dec({'4e' 'a4'}), 'unicode')  native2unicode(hex2dec({'4e' '92'}), 'unicode')  native2unicode(hex2dec({'76' '84'}), 'unicode')  native2unicode(hex2dec({'4e' '09'}), 'unicode')  native2unicode(hex2dec({'7e' 'f4'}), 'unicode')  native2unicode(hex2dec({'50' '3c'}), 'unicode') ]);
model.result.table('tbl1').label([native2unicode(hex2dec({'63' 'a2'}), 'unicode')  native2unicode(hex2dec({'94' '88'}), 'unicode')  native2unicode(hex2dec({'88' '68'}), 'unicode') ' 1']);

model.component('comp1').view('view1').set('renderwireframe', true);
model.component('comp1').view('view1').set('showgrid', false);
model.component('comp1').view('view1').set('showaxisorientation', false);
model.component('comp1').view('view1').set('scenelight', false);
model.component('comp1').view('view1').set('transparency', true);
model.component('comp1').view('view3').label([native2unicode(hex2dec({'89' 'c6'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode') ' 3.1']);
model.component('comp1').view('view4').label([native2unicode(hex2dec({'89' 'c6'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode') ' 4']);

model.component('comp1').material('mat1').label('Air');
model.component('comp1').material('mat1').set('family', 'air');
model.component('comp1').material('mat1').propertyGroup('def').label('Basic');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').label('Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('pieces', {'200.0' '1600.0' '-8.38278E-7+8.35717342E-8*T^1-7.69429583E-11*T^2+4.6437266E-14*T^3-1.06585607E-17*T^4'});
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('eta').set('fununit', 'Pa*s');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').label('Piecewise 2');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('pieces', {'200.0' '1600.0' '1047.63657-0.372589265*T^1+9.45304214E-4*T^2-6.02409443E-7*T^3+1.2858961E-10*T^4'});
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('Cp').set('fununit', 'J/(kg*K)');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').label('Analytic');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('expr', 'pA*0.02897/R_const[K*mol/J]/T');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('args', {'pA' 'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('fununit', 'kg/m^3');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('argunit', {'Pa' 'K'});
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('plotargs', {'pA' '101325' '101325'; 'T' '273.15' '293.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('k').label('Piecewise 3');
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('pieces', {'200.0' '1600.0' '-0.00227583562+1.15480022E-4*T^1-7.90252856E-8*T^2+4.11702505E-11*T^3-7.43864331E-15*T^4'});
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('def').func('k').set('fununit', 'W/(m*K)');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').label('Analytic 2');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('expr', 'sqrt(1.4*R_const[K*mol/J]/0.02897*T)');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('args', {'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('fununit', 'm/s');
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('argunit', {'K'});
model.component('comp1').material('mat1').propertyGroup('def').func('cs').set('plotargs', {'T' '273.15' '373.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('an1').label('Analytic 1');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('funcname', 'alpha_p');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('expr', '-1/rho(pA,T)*d(rho(pA,T),T)');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('args', {'pA' 'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('fununit', '1/K');
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('argunit', {'Pa' 'K'});
model.component('comp1').material('mat1').propertyGroup('def').func('an1').set('plotargs', {'pA' '101325' '101325'; 'T' '273.15' '373.15'});
model.component('comp1').material('mat1').propertyGroup('def').func('an2').label('Analytic 2a');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('funcname', 'muB');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('expr', '0.6*eta(T)');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('args', {'T'});
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('fununit', 'Pa*s');
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('argunit', {'K'});
model.component('comp1').material('mat1').propertyGroup('def').func('an2').set('plotargs', {'T' '200' '1600'});
model.component('comp1').material('mat1').propertyGroup('def').set('thermalexpansioncoefficient', {'alpha_p(pA,T)' '0' '0' '0' 'alpha_p(pA,T)' '0' '0' '0' 'alpha_p(pA,T)'});
model.component('comp1').material('mat1').propertyGroup('def').set('molarmass', '0.02897[kg/mol]');
model.component('comp1').material('mat1').propertyGroup('def').set('bulkviscosity', 'muB(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat1').propertyGroup('def').set('relpermittivity', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat1').propertyGroup('def').set('dynamicviscosity', 'eta(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('ratioofspecificheat', '1.4');
model.component('comp1').material('mat1').propertyGroup('def').set('electricconductivity', {'0[S/m]' '0' '0' '0' '0[S/m]' '0' '0' '0' '0[S/m]'});
model.component('comp1').material('mat1').propertyGroup('def').set('heatcapacity', 'Cp(T)');
model.component('comp1').material('mat1').propertyGroup('def').set('density', 'rho(pA,T)');
model.component('comp1').material('mat1').propertyGroup('def').set('thermalconductivity', {'k(T)' '0' '0' '0' 'k(T)' '0' '0' '0' 'k(T)'});
model.component('comp1').material('mat1').propertyGroup('def').set('soundspeed', 'cs(T)');
model.component('comp1').material('mat1').propertyGroup('def').addInput('temperature');
model.component('comp1').material('mat1').propertyGroup('def').addInput('pressure');
model.component('comp1').material('mat1').propertyGroup('RefractiveIndex').label('Refractive index');
model.component('comp1').material('mat1').propertyGroup('RefractiveIndex').set('n', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat1').propertyGroup('NonlinearModel').label('Nonlinear model');
model.component('comp1').material('mat1').propertyGroup('NonlinearModel').set('BA', '(def.gamma+1)/2');
model.component('comp1').material('mat1').propertyGroup('idealGas').label('Ideal gas');
model.component('comp1').material('mat1').propertyGroup('idealGas').func('Cp').label('Piecewise 2');
model.component('comp1').material('mat1').propertyGroup('idealGas').func('Cp').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('idealGas').func('Cp').set('pieces', {'200.0' '1600.0' '1047.63657-0.372589265*T^1+9.45304214E-4*T^2-6.02409443E-7*T^3+1.2858961E-10*T^4'});
model.component('comp1').material('mat1').propertyGroup('idealGas').func('Cp').set('argunit', 'K');
model.component('comp1').material('mat1').propertyGroup('idealGas').func('Cp').set('fununit', 'J/(kg*K)');
model.component('comp1').material('mat1').propertyGroup('idealGas').set('Rs', 'R_const/Mn');
model.component('comp1').material('mat1').propertyGroup('idealGas').set('heatcapacity', 'Cp(T)');
model.component('comp1').material('mat1').propertyGroup('idealGas').set('ratioofspecificheat', '1.4');
model.component('comp1').material('mat1').propertyGroup('idealGas').set('molarmass', '0.02897');
model.component('comp1').material('mat1').propertyGroup('idealGas').addInput('temperature');
model.component('comp1').material('mat1').propertyGroup('idealGas').addInput('pressure');
model.component('comp1').material('mat1').materialType('nonSolid');
model.component('comp1').material('mat3').label('FR4 (Circuit Board)');
model.component('comp1').material('mat3').set('family', 'pcbgreen');
model.component('comp1').material('mat3').propertyGroup('def').label('Basic');
model.component('comp1').material('mat3').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat3').propertyGroup('def').set('electricconductivity', {'0.004[S/m]' '0' '0' '0' '0.004[S/m]' '0' '0' '0' '0.004[S/m]'});
model.component('comp1').material('mat3').propertyGroup('def').set('relpermittivity', {'4.5' '0' '0' '0' '4.5' '0' '0' '0' '4.5'});
model.component('comp1').material('mat3').propertyGroup('def').set('thermalexpansioncoefficient', {'18e-6[1/K]' '0' '0' '0' '18e-6[1/K]' '0' '0' '0' '18e-6[1/K]'});
model.component('comp1').material('mat3').propertyGroup('def').set('heatcapacity', '900[J/(kg*K)]');
model.component('comp1').material('mat3').propertyGroup('def').set('density', '2700[kg/m^3]');
model.component('comp1').material('mat3').propertyGroup('def').set('thermalconductivity', {'1.3[W/(m*K)]' '0' '0' '0' '1.3[W/(m*K)]' '0' '0' '0' '1.3[W/(m*K)]'});
model.component('comp1').material('mat3').propertyGroup('Enu').label('Young''s modulus and Poisson''s ratio');
model.component('comp1').material('mat3').propertyGroup('Enu').set('E', '22[GPa]');
model.component('comp1').material('mat3').propertyGroup('Enu').set('nu', '0.15');
model.component('comp1').material('mat5').label('Silicon');
model.component('comp1').material('mat5').set('family', 'custom');
model.component('comp1').material('mat5').set('customspecular', [0.7843137254901961 1 1]);
model.component('comp1').material('mat5').set('customdiffuse', [0.6666666666666666 0.6666666666666666 0.7058823529411765]);
model.component('comp1').material('mat5').set('customambient', [0.6666666666666666 0.6666666666666666 0.7058823529411765]);
model.component('comp1').material('mat5').set('fresnel', 0.7);
model.component('comp1').material('mat5').set('metallic', 0);
model.component('comp1').material('mat5').set('pearl', 0);
model.component('comp1').material('mat5').set('diffusewrap', 0);
model.component('comp1').material('mat5').set('clearcoat', 0);
model.component('comp1').material('mat5').set('reflectance', 0);
model.component('comp1').material('mat5').propertyGroup('def').label('Basic');
model.component('comp1').material('mat5').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat5').propertyGroup('def').set('electricconductivity', {'1e-12[S/m]' '0' '0' '0' '1e-12[S/m]' '0' '0' '0' '1e-12[S/m]'});
model.component('comp1').material('mat5').propertyGroup('def').set('thermalexpansioncoefficient', {'2.6e-6[1/K]' '0' '0' '0' '2.6e-6[1/K]' '0' '0' '0' '2.6e-6[1/K]'});
model.component('comp1').material('mat5').propertyGroup('def').set('heatcapacity', '770[J/(kg*K)]');
model.component('comp1').material('mat5').propertyGroup('def').set('relpermittivity', {'11.7' '0' '0' '0' '11.7' '0' '0' '0' '11.7'});
model.component('comp1').material('mat5').propertyGroup('def').set('density', '2329[kg/m^3]');
model.component('comp1').material('mat5').propertyGroup('def').set('thermalconductivity', {'156[W/(m*K)]' '0' '0' '0' '156[W/(m*K)]' '0' '0' '0' '156[W/(m*K)]'});
model.component('comp1').material('mat5').propertyGroup('Enu').label('Young''s modulus and Poisson''s ratio');
model.component('comp1').material('mat5').propertyGroup('Enu').set('E', '170[GPa]');
model.component('comp1').material('mat5').propertyGroup('Enu').set('nu', '0.28');
model.component('comp1').material('mat5').propertyGroup('RefractiveIndex').label('Refractive index');
model.component('comp1').material('mat5').propertyGroup('RefractiveIndex').set('n', {'3.48' '0' '0' '0' '3.48' '0' '0' '0' '3.48'});
model.component('comp1').material('mat6').label([native2unicode(hex2dec({'71' '0a'}), 'unicode')  native2unicode(hex2dec({'65' '99'}), 'unicode')  native2unicode(hex2dec({'5c' '42'}), 'unicode') ]);
model.component('comp1').material('mat6').propertyGroup('def').set('thermalconductivity', {'54' '0' '0' '0' '54' '0' '0' '0' '54'});
model.component('comp1').material('mat6').propertyGroup('def').set('heatcapacity', '230');
model.component('comp1').material('mat6').propertyGroup('def').set('density', '7300');
model.component('comp1').material('mat6').propertyGroup('shell').set('lth', '0.1[mm]');
model.component('comp1').material('mat7').active(false);
model.component('comp1').material('mat7').label('Alumina');
model.component('comp1').material('mat7').set('family', 'aluminum');
model.component('comp1').material('mat7').propertyGroup('def').label('Basic');
model.component('comp1').material('mat7').propertyGroup('def').set('thermalexpansioncoefficient', {'8e-6[1/K]' '0' '0' '0' '8e-6[1/K]' '0' '0' '0' '8e-6[1/K]'});
model.component('comp1').material('mat7').propertyGroup('def').set('heatcapacity', '900[J/(kg*K)]');
model.component('comp1').material('mat7').propertyGroup('def').set('density', '3900[kg/m^3]');
model.component('comp1').material('mat7').propertyGroup('def').set('thermalconductivity', {'27[W/(m*K)]' '0' '0' '0' '27[W/(m*K)]' '0' '0' '0' '27[W/(m*K)]'});
model.component('comp1').material('mat7').propertyGroup('Enu').label('Young''s modulus and Poisson''s ratio');
model.component('comp1').material('mat7').propertyGroup('Enu').set('E', '300[GPa]');
model.component('comp1').material('mat7').propertyGroup('Enu').set('nu', '0.222');
model.component('comp1').material('mat8').label('Copper');
model.component('comp1').material('mat8').set('family', 'copper');
model.component('comp1').material('mat8').propertyGroup('def').label('Basic');
model.component('comp1').material('mat8').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat8').propertyGroup('def').set('electricconductivity', {'5.998e7[S/m]' '0' '0' '0' '5.998e7[S/m]' '0' '0' '0' '5.998e7[S/m]'});
model.component('comp1').material('mat8').propertyGroup('def').set('thermalexpansioncoefficient', {'17e-6[1/K]' '0' '0' '0' '17e-6[1/K]' '0' '0' '0' '17e-6[1/K]'});
model.component('comp1').material('mat8').propertyGroup('def').set('heatcapacity', '385[J/(kg*K)]');
model.component('comp1').material('mat8').propertyGroup('def').set('relpermittivity', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('comp1').material('mat8').propertyGroup('def').set('density', '8960[kg/m^3]');
model.component('comp1').material('mat8').propertyGroup('def').set('thermalconductivity', {'400[W/(m*K)]' '0' '0' '0' '400[W/(m*K)]' '0' '0' '0' '400[W/(m*K)]'});
model.component('comp1').material('mat8').propertyGroup('Enu').label('Young''s modulus and Poisson''s ratio');
model.component('comp1').material('mat8').propertyGroup('Enu').set('E', '110[GPa]');
model.component('comp1').material('mat8').propertyGroup('Enu').set('nu', '0.35');
model.component('comp1').material('mat8').propertyGroup('linzRes').label('Linearized resistivity');
model.component('comp1').material('mat8').propertyGroup('linzRes').set('rho0', '1.72e-8[ohm*m]');
model.component('comp1').material('mat8').propertyGroup('linzRes').set('alpha', '0.0039[1/K]');
model.component('comp1').material('mat8').propertyGroup('linzRes').set('Tref', '298[K]');
model.component('comp1').material('mat8').propertyGroup('linzRes').addInput('temperature');

model.component('comp1').physics('ht').feature('fluid1').set('u', [0; 0; 0.05]);
model.component('comp1').physics('ht').feature('hs1').set('heatSourceType', 'HeatRate');
model.component('comp1').physics('ht').feature('hs1').set('P0', 8);
model.component('comp1').physics('ht').feature('sls1').set('shelllist', 'none');
model.component('comp1').physics('ht').feature('temp1').active(false);
model.component('comp1').physics('ht').feature('hs2').set('heatSourceType', 'HeatRate');
model.component('comp1').physics('ht').feature('hs2').set('P0', 5);
model.component('comp1').physics('ht').feature('hs3').set('heatSourceType', 'HeatRate');
model.component('comp1').physics('ht').feature('hs3').set('P0', 4);
model.component('comp1').physics('ht').feature('hs4').set('heatSourceType', 'HeatRate');
model.component('comp1').physics('ht').feature('hs4').set('P0', 8);
model.component('comp1').physics('ht').feature('hs5').set('heatSourceType', 'HeatRate');
model.component('comp1').physics('ht').feature('hs5').set('P0', 7);
model.component('comp1').physics('ht').feature('hf1').set('HeatFluxType', 'ConvectiveHeatFlux');
model.component('comp1').physics('ht').feature('hf1').set('h', 10);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% change mesh
model.component('comp1').mesh('mesh1').feature('size').set('hauto', num2str(level));
%model.component('comp1').mesh('mesh1').feature('size').set('hauto', '5');
model.component('comp1').mesh('mesh1').run;

model.component('comp1').probe('dom9').label('CHIP1');
model.component('comp1').probe('dom9').set('type', 'maximum');
model.component('comp1').probe('dom9').set('unit', 'degC');
model.component('comp1').probe('dom9').set('table', 'tbl1');
model.component('comp1').probe('dom9').set('window', 'window1');
model.component('comp1').probe('dom8').label('CHIP2');
model.component('comp1').probe('dom8').set('type', 'maximum');
model.component('comp1').probe('dom8').set('unit', 'degC');
model.component('comp1').probe('dom8').set('table', 'tbl1');
model.component('comp1').probe('dom8').set('window', 'window1');
model.component('comp1').probe('dom7').label('CHIP3');
model.component('comp1').probe('dom7').set('type', 'maximum');
model.component('comp1').probe('dom7').set('unit', 'degC');
model.component('comp1').probe('dom7').set('table', 'tbl1');
model.component('comp1').probe('dom7').set('window', 'window1');
model.component('comp1').probe('dom6').label('CHIP4');
model.component('comp1').probe('dom6').set('type', 'maximum');
model.component('comp1').probe('dom6').set('unit', 'degC');
model.component('comp1').probe('dom6').set('table', 'tbl1');
model.component('comp1').probe('dom6').set('window', 'window1');
model.component('comp1').probe('dom5').label('CHIP5');
model.component('comp1').probe('dom5').set('type', 'maximum');
model.component('comp1').probe('dom5').set('unit', 'degC');
model.component('comp1').probe('dom5').set('table', 'tbl1');
model.component('comp1').probe('dom5').set('window', 'window1');

model.study.create('std1');
model.study('std1').create('stat', 'Stationary');

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('s1', 'Stationary');
model.sol('sol1').feature('s1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('s1').create('d1', 'Direct');
model.sol('sol1').feature('s1').create('i1', 'Iterative');
model.sol('sol1').feature('s1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol1').feature('s1').feature.remove('fcDef');

model.result.dataset.create('dset2', 'Solution');
model.result.dataset.create('max3', 'Maximum');
model.result.dataset.create('max4', 'Maximum');
model.result.dataset.create('max5', 'Maximum');
model.result.dataset.create('max6', 'Maximum');
model.result.dataset.create('max7', 'Maximum');
model.result.dataset('dset1').selection.geom('geom1', 3);
model.result.dataset('dset1').selection.set([2 4]);
model.result.dataset('dset2').set('probetag', 'dom5');
model.result.dataset('max3').set('probetag', 'dom5');
model.result.dataset('max3').set('data', 'dset2');
model.result.dataset('max3').selection.geom('geom1', 3);
model.result.dataset('max3').selection.set([4]);
model.result.dataset('max4').set('probetag', 'dom6');
model.result.dataset('max4').set('data', 'dset2');
model.result.dataset('max4').selection.geom('geom1', 3);
model.result.dataset('max4').selection.set([6]);
model.result.dataset('max5').set('probetag', 'dom7');
model.result.dataset('max5').set('data', 'dset2');
model.result.dataset('max5').selection.geom('geom1', 3);
model.result.dataset('max5').selection.set([5]);
model.result.dataset('max6').set('probetag', 'dom8');
model.result.dataset('max6').set('data', 'dset2');
model.result.dataset('max6').selection.geom('geom1', 3);
model.result.dataset('max6').selection.set([7]);
model.result.dataset('max7').set('probetag', 'dom9');
model.result.dataset('max7').set('data', 'dset2');
model.result.dataset('max7').selection.geom('geom1', 3);
model.result.dataset('max7').selection.set([3]);
model.result.numerical.create('pev7', 'EvalPoint');
model.result.numerical.create('pev6', 'EvalPoint');
model.result.numerical.create('pev5', 'EvalPoint');
model.result.numerical.create('pev4', 'EvalPoint');
model.result.numerical.create('pev3', 'EvalPoint');
model.result.numerical('pev7').set('probetag', 'dom9');
model.result.numerical('pev6').set('probetag', 'dom8');
model.result.numerical('pev5').set('probetag', 'dom7');
model.result.numerical('pev4').set('probetag', 'dom6');
model.result.numerical('pev3').set('probetag', 'dom5');
model.result.create('pg1', 'PlotGroup3D');
model.result.create('pg2', 'PlotGroup1D');
model.result('pg1').selection.geom('geom1', 3);
model.result('pg1').selection.set([2 3 4 5 6 7]);
model.result('pg1').create('vol1', 'Volume');
model.result('pg2').set('probetag', 'window1_default');
model.result('pg2').create('tblp2', 'Table');
model.result('pg2').create('tblp3', 'Table');
model.result('pg2').create('tblp4', 'Table');
model.result('pg2').feature('tblp4').set('probetag', 'dom1,dom2,dom5,dom6,dom7,dom8,dom9');

model.component('comp1').probe('dom9').genResult([]);
model.component('comp1').probe('dom8').genResult([]);
model.component('comp1').probe('dom7').genResult([]);
model.component('comp1').probe('dom6').genResult([]);
model.component('comp1').probe('dom5').genResult([]);

model.sol('sol1').attach('std1');
model.sol('sol1').feature('st1').label([native2unicode(hex2dec({'7f' '16'}), 'unicode')  native2unicode(hex2dec({'8b' 'd1'}), 'unicode')  native2unicode(hex2dec({'65' 'b9'}), 'unicode')  native2unicode(hex2dec({'7a' '0b'}), 'unicode') ': ' native2unicode(hex2dec({'7a' '33'}), 'unicode')  native2unicode(hex2dec({'60' '01'}), 'unicode') ]);
model.sol('sol1').feature('v1').label([native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'53' 'd8'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode') ' 1.1']);
model.sol('sol1').feature('s1').label([native2unicode(hex2dec({'7a' '33'}), 'unicode')  native2unicode(hex2dec({'60' '01'}), 'unicode')  native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode') ' 1.1']);
model.sol('sol1').feature('s1').feature('dDef').label([native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode') ' 2']);
model.sol('sol1').feature('s1').feature('aDef').label([native2unicode(hex2dec({'9a' 'd8'}), 'unicode')  native2unicode(hex2dec({'7e' 'a7'}), 'unicode') ' 1']);
model.sol('sol1').feature('s1').feature('fc1').label([native2unicode(hex2dec({'51' '68'}), 'unicode')  native2unicode(hex2dec({'80' '26'}), 'unicode')  native2unicode(hex2dec({'54' '08'}), 'unicode') ' 1.1']);
model.sol('sol1').feature('s1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('s1').feature('fc1').set('initstep', 0.01);
model.sol('sol1').feature('s1').feature('fc1').set('minstep', 1.0E-6);
model.sol('sol1').feature('s1').feature('fc1').set('maxiter', 50);
model.sol('sol1').feature('s1').feature('fc1').set('termonres', false);
model.sol('sol1').feature('s1').feature('d1').label([native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode')  native2unicode(hex2dec({'4f' '20'}), 'unicode')  native2unicode(hex2dec({'70' 'ed'}), 'unicode')  native2unicode(hex2dec({'53' 'd8'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode') ' (ht)']);
model.sol('sol1').feature('s1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('s1').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol1').feature('s1').feature('i1').label(['AMG' native2unicode(hex2dec({'ff' '0c'}), 'unicode')  native2unicode(hex2dec({'4f' '20'}), 'unicode')  native2unicode(hex2dec({'70' 'ed'}), 'unicode')  native2unicode(hex2dec({'53' 'd8'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode') ' (ht)']);
model.sol('sol1').feature('s1').feature('i1').set('nlinnormuse', true);
model.sol('sol1').feature('s1').feature('i1').set('rhob', 20);
model.sol('sol1').feature('s1').feature('i1').feature('ilDef').label([native2unicode(hex2dec({'4e' '0d'}), 'unicode')  native2unicode(hex2dec({'5b' '8c'}), 'unicode')  native2unicode(hex2dec({'51' '68'}), 'unicode') ' LU ' native2unicode(hex2dec({'52' '06'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').label([native2unicode(hex2dec({'59' '1a'}), 'unicode')  native2unicode(hex2dec({'91' 'cd'}), 'unicode')  native2unicode(hex2dec({'7f' '51'}), 'unicode')  native2unicode(hex2dec({'68' '3c'}), 'unicode') ' 1.1']);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('prefun', 'saamg');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('maxcoarsedof', 50000);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('saamgcompwise', true);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').set('usesmooth', false);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').label([native2unicode(hex2dec({'98' '84'}), 'unicode')  native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'6e' 'd1'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode') ' 1']);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 2');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').label('SOR 1.1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.9);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').label([native2unicode(hex2dec({'54' '0e'}), 'unicode')  native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'6e' 'd1'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode') ' 1']);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 2');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').label('SOR 1.1');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.9);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').label([native2unicode(hex2dec({'7c' '97'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode') ' 1']);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('dDef').label([native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode') ' 2']);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').label([native2unicode(hex2dec({'76' 'f4'}), 'unicode')  native2unicode(hex2dec({'63' 'a5'}), 'unicode') ' 1.1']);
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('s1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol1').runAll;

model.result('pg1').set('showlegendsmaxmin', true);
model.result('pg1').feature('vol1').set('unit', 'degC');
model.result('pg1').feature('vol1').set('resolution', 'normal');
model.result('pg2').set('xlabel', [native2unicode(hex2dec({'6e' '29'}), 'unicode')  native2unicode(hex2dec({'5e' 'a6'}), 'unicode') ' (degC), CHIP1']);
model.result('pg2').set('windowtitle', [native2unicode(hex2dec({'63' 'a2'}), 'unicode')  native2unicode(hex2dec({'94' '88'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode')  native2unicode(hex2dec({'20' '1c'}), 'unicode') '2' native2unicode(hex2dec({'20' '1d'}), 'unicode') ]);
model.result('pg2').set('xlabelactive', false);
model.result('pg2').feature('tblp2').label([native2unicode(hex2dec({'63' 'a2'}), 'unicode')  native2unicode(hex2dec({'94' '88'}), 'unicode')  native2unicode(hex2dec({'88' '68'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode') ' 2']);
model.result('pg2').feature('tblp2').set('table', 'tbl1');
model.result('pg2').feature('tblp2').set('plotcolumninput', 'manual');
model.result('pg2').feature('tblp2').set('legend', true);
model.result('pg2').feature('tblp3').label([native2unicode(hex2dec({'63' 'a2'}), 'unicode')  native2unicode(hex2dec({'94' '88'}), 'unicode')  native2unicode(hex2dec({'88' '68'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode') ' 3']);
model.result('pg2').feature('tblp3').set('table', 'tbl1');
model.result('pg2').feature('tblp3').set('plotcolumninput', 'manual');
model.result('pg2').feature('tblp3').set('legend', true);
model.result('pg2').feature('tblp4').label([native2unicode(hex2dec({'63' 'a2'}), 'unicode')  native2unicode(hex2dec({'94' '88'}), 'unicode')  native2unicode(hex2dec({'88' '68'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode') ' 4']);
model.result('pg2').feature('tblp4').set('table', 'tbl1');
model.result('pg2').feature('tblp4').set('plotcolumninput', 'manual');
model.result('pg2').feature('tblp4').set('legend', true);
model.result('pg2').feature.remove('tblp5');

model.sol('sol1').runAll;
model.result('pg1').run;


tabl = mphtable(model,'tbl1');
T1= tabl.data(1);
T2= tabl.data(2);
T3= tabl.data(3);
T4= tabl.data(4);
T5= tabl.data(5);

%%%%%%%%%%%%%%%%  保存模型和数�?
% filename = sprintf('tets.mph');
% mphsave(filename);
% % % Tfilename = sprintf('TanZhen%03d.csv',i);
% % % model.result.table('tbl2').save(Tfilename );

end


%out = model;
