% 两个组件是否重叠
function overlap = isOverlapping(pos1, L1, W1, pos2, L2, W2)
    interval = 1;  %原件之间的最小间隔
    overlap = ~(pos1(1) + L1 + interval <= pos2(1) || ...
                pos1(1) >= pos2(1) + L2 + interval || ...
                pos1(2) + W1 + interval <= pos2(2) || ...
                pos1(2) >= pos2(2) + W2 + interval);
end